apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: app
    repoURL: https://github.com/prajyotpotraje11/Argocd.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      enabled: true
