apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default

  source:
    repoURL: https://github.com/prajyotpotraje11/Argocd.git
    targetRevision: HEAD
    path: app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
