apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp2
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: jotaro02/flaskapp
        
        ports:
        - containerPort: 5000
